; ---------------------------------------------------------------------------
; AY-3-8912 sound (128K Spectrum or a 48K machine with an AY interface)
;
; Effect data lives in sound_ay_data.asm, generated by tools/tia2ay.py from
; the per-frame register behaviour of the original Atari 2600 River Raid
; sound routine. Channel A carries the jet engine noise, the low-fuel
; warning tone and the life-lost noise burst; channel B carries the player
; missile sweep and the tank shell sweep; channel C carries the destroyed-
; actor crackle, the water splash and the refuelling pings.
; ---------------------------------------------------------------------------

init_ay_sound:
    ; Standard AY writes are harmless on a stock 48K machine. In the Timex
    ; build, detect a real 2068 first so a TC2048 never receives writes
    ; through its even $F6 port while no AY is present.
    call detect_ay_output
    xor a
    ld (shot_sound_timer),a
    ld (missile_sound_left),a
    ld (c_sound_left),a
    ld (c_sound_kind),a
    ld (a_burst_left),a
    ld (crash_sound_kind),a
    ld (siren_tone_active),a
    ld (siren_phase),a
    ld a,255
    ld (ay_last_speed),a
    call refresh_ay_mixer
    ld e,0
    ld a,8
    call ay_write_register
    ld e,0
    ld a,9
    call ay_write_register
    ld e,0
    ld a,10
    call ay_write_register
    jp update_ay_engine

detect_ay_output:
#if TIMEX_HICOLOR
    jp detect_timex_2068_ay
#else
    ld a,1                         ; standard build keeps the existing AY path
    ld (timex_ay_present),a
    ret
#endif

#if TIMEX_HICOLOR
detect_timex_2068_ay:
    ; TC2068 and TS2068 HOME ROMs contain "Timex" at $113D. The TC2048 ROM
    ; does not, so this read-only test separates native-AY 2068 machines from
    ; the otherwise compatible, beeper-only TC2048 before touching $F5/$F6.
    ld hl,0x113d
    ld de,timex_rom_signature
    ld b,5
detect_timex_2068_byte:
    ld a,(de)
    cp (hl)
    jr nz,detect_timex_ay_missing
    inc de
    inc hl
    djnz detect_timex_2068_byte
    ld a,1
    ld (timex_ay_present),a
    ret
detect_timex_ay_missing:
    xor a
    ld (timex_ay_present),a
    ret
#endif

refresh_ay_mixer:
    ; Recompute R7 from the current channel modes; a zero bit enables.
    ; Tone B stays enabled for the weapon sweeps in every state.
    ld a,(c_sound_kind)
    ld e,0x31                       ; idle or ding: clean tone on channel C
    cp 1
    jr c,apply_mixer_a_mode
    ld e,0x15                       ; impact crackle: channel C noise only
    jr z,apply_mixer_a_mode
    cp 3
    ld e,0x11                       ; splash: channel C tone plus noise
    jr c,apply_mixer_a_mode
    ld e,0x31
apply_mixer_a_mode:
    ld a,(siren_tone_active)
    or a
    jr z,write_ay_mixer
    ld a,e
    xor 0x09                        ; warning tone: channel A noise -> tone
    ld e,a
write_ay_mixer:
    ld a,7
    jp ay_write_register

update_ay_sound:
    call update_ay_channel_a
    call update_ay_channel_b
    jp update_ay_channel_c

; ---------------------------------------------------------------------------
; Channel A: life-lost burst, low-fuel warning, jet engine
; ---------------------------------------------------------------------------

update_ay_channel_a:
    ld a,(a_burst_left)
    or a
    jr nz,play_a_burst_frame
    ld a,(game_state)
    or a
    ret nz                          ; the crash pause keeps the engine silent
    ld a,(fuel_level)
    cp 12                           ; matches the original's $40/$FF threshold
    jr c,update_ay_siren
    ld a,(siren_tone_active)
    or a
    jp z,update_ay_engine
    call stop_ay_siren
    jp update_ay_engine

play_a_burst_frame:
    dec a
    ld (a_burst_left),a
    ld hl,(a_burst_ptr)
    ld e,(hl)
    inc hl
    ld (a_burst_ptr),hl
    ld a,8
    jp ay_write_register

stop_ay_siren:
    xor a
    ld (siren_tone_active),a
    ld (siren_phase),a
    ld a,255
    ld (ay_last_speed),a            ; force the engine registers back on
    jp refresh_ay_mixer

update_ay_siren:
    ; The original interleaves a rising warning tone with the jet noise on
    ; one channel over a fixed cycle; zero periods mark the engine frames.
    ld a,(siren_phase)
    ld c,a
    inc a
    ld hl,siren_cycle_frames
    cp (hl)
    jr c,store_siren_phase
    xor a
store_siren_phase:
    ld (siren_phase),a
    ld a,c
    add a,a                         ; two bytes per cycle entry
    ld e,a
    ld d,0
    ld hl,siren_period_table
    add hl,de
    ld e,(hl)
    inc hl
    ld d,(hl)
    ld a,d
    or e
    jr z,siren_engine_frame
    ld a,(siren_tone_active)
    or a
    jr nz,siren_tone_ready
    ld a,1
    ld (siren_tone_active),a
    call refresh_ay_mixer
siren_tone_ready:
    ld a,0                          ; channel A tone period, low byte
    call ay_write_register
    ld e,d
    ld a,1                          ; channel A tone period, high nibble
    call ay_write_register
    ld a,(siren_volume)
    ld e,a
    ld a,8
    jp ay_write_register

siren_engine_frame:
    ld a,(siren_tone_active)
    or a
    jp z,update_ay_engine
    xor a
    ld (siren_tone_active),a
    ld a,255
    ld (ay_last_speed),a
    call refresh_ay_mixer
    jr update_ay_engine

update_ay_engine:
    ; requested_speed is the stable 0/1/2 control value. Using speed_pixels
    ; here would make the slow 0.5x mode alternate between two engine pitches.
    ld a,(requested_speed)
    ld b,a
    ld a,(ay_last_speed)
    cp b
    ret z
    ld a,b
    ld (ay_last_speed),a
    ld e,a
    ld d,0
    ld hl,ay_engine_noise_periods
    add hl,de
    ld e,(hl)
    ld a,6                          ; AY noise period: smaller means higher
    call ay_write_register

    ld a,(requested_speed)
    ld e,a
    ld d,0
    ld hl,ay_engine_volumes
    add hl,de
    ld e,(hl)
    ld a,8
    jp ay_write_register

start_ay_crash:
    ; Losing the jet. Running dry selects the original's higher, longer
    ; noise burst (sound id 2); any other crash uses the life-lost burst
    ; (id 1) layered with the same crackle a destroyed actor makes.
    ld a,(crash_sound_kind)
    or a
    jr nz,start_fuel_out_burst
    ld hl,crash_sound_table
    ld (a_burst_ptr),hl
    ld a,(crash_sound_frames)
    ld (a_burst_left),a
    ld a,(crash_sound_noise)
    ld e,a
    ld a,6
    call ay_write_register
    jp start_ay_explosion

start_fuel_out_burst:
    xor a
    ld (crash_sound_kind),a
    ld hl,fuelout_sound_table
    ld (a_burst_ptr),hl
    ld a,(fuelout_sound_frames)
    ld (a_burst_left),a
    ld a,(fuelout_sound_noise)
    ld e,a
    ld a,6
    jp ay_write_register

; ---------------------------------------------------------------------------
; Channel B: player missile sweep, tank shell sweep
; ---------------------------------------------------------------------------

start_missile_sound:
    ; The player's shot replays the original's descending frequency sweep.
    ld hl,missile_sound_table
    ld (missile_sound_ptr),hl
    ld a,(missile_sound_frames)
    ld (missile_sound_left),a
    xor a
    ld (shot_sound_timer),a         ; the newest weapon owns channel B
    ret

start_tank_shot_sound:
    ; The shore gun keeps its pre-existing sweep (no Atari counterpart):
    ; higher and sharper than the player's missile.
    ld a,25
    ld (shot_sound_timer),a
    ld a,12
    ld (shot_sound_period),a
    xor a
    ld (missile_sound_left),a       ; the newest weapon owns channel B
    ret

update_ay_channel_b:
    ld a,(missile_sound_left)
    or a
    jr nz,play_missile_frame
    ld a,(shot_sound_timer)
    or a
    ret z
    ; tank shell sweep: period grows by eight each frame while the volume
    ; fades, producing an aggressive downward chirp
    dec a
    ld (shot_sound_timer),a
    ld d,a

    ld a,(shot_sound_period)
    ld e,a
    ld a,2                          ; channel B tone period, low byte
    call ay_write_register
    ld e,0
    ld a,3                          ; period never exceeds 255 in this sweep
    call ay_write_register

    ld a,d
    inc a
    srl a
    ld e,a
    ld a,9                          ; channel B amplitude
    call ay_write_register

    ld a,(shot_sound_period)
    add a,8
    ld (shot_sound_period),a
    ret

play_missile_frame:
    dec a
    ld (missile_sound_left),a
    ld hl,(missile_sound_ptr)
    ld e,(hl)
    ld a,2                          ; channel B tone period, low byte
    call ay_write_register
    inc hl
    ld e,(hl)
    ld a,3                          ; channel B tone period, high byte
    call ay_write_register
    inc hl
    ld e,(hl)
    ld a,9                          ; channel B amplitude for this frame
    call ay_write_register
    inc hl
    ld (missile_sound_ptr),hl
    ret

; ---------------------------------------------------------------------------
; Channel C: destroyed-actor crackle, splash, refuelling pings
; ---------------------------------------------------------------------------

start_ay_explosion:
    ; A destroyed actor restarts the original's noise burst, whose frequency
    ; is re-randomised every frame (the sequence is baked into the table).
    ld a,1
    ld (c_sound_kind),a
    ld hl,impact_sound_table
    ld (c_sound_ptr),hl
    ld a,(impact_sound_frames)
    ld (c_sound_left),a
    jp refresh_ay_mixer

start_ay_splash:
    ; A water landing keeps the softer pre-existing tone-plus-noise thud.
    ld a,2
    ld (c_sound_kind),a
    ld hl,splash_sound_table
    ld (c_sound_ptr),hl
    ld a,(splash_sound_frames)
    ld (c_sound_left),a
    ld e,31                         ; coarse noise under the falling tone
    ld a,6
    call ay_write_register
    jp refresh_ay_mixer

start_fuel_ding:
    ; Refuelling ping, retried every contact frame. A running channel C
    ; effect blocks the retrigger: impacts keep priority, and a playing
    ; ping finishing first is what creates the original's repeating pulse.
    ld a,(c_sound_left)
    or a
    ret nz
    ld a,(fuel_level)
    cp 48
    jr c,ding_normal_pitch
    ld a,(ding_period_full)         ; full tank: exactly one octave higher
    jr set_ding_period
ding_normal_pitch:
    ld a,(ding_period_normal)
set_ding_period:
    ld e,a
    ld a,4                          ; channel C tone period, low byte
    call ay_write_register
    ld e,0
    ld a,5
    call ay_write_register
    ld a,3
    ld (c_sound_kind),a
    ld hl,ding_volume_table
    ld (c_sound_ptr),hl
    ld a,(ding_sound_frames)
    ld (c_sound_left),a
    jp refresh_ay_mixer

update_ay_channel_c:
    ld a,(c_sound_left)
    or a
    ret z
    dec a
    ld (c_sound_left),a
    ld a,(c_sound_kind)
    cp 3
    jr z,play_ding_frame
    cp 1
    jr z,play_impact_frame
    ; splash frame: falling tone over the steady coarse noise
    ld hl,(c_sound_ptr)
    ld e,(hl)
    ld a,4                          ; channel C tone period, low byte
    call ay_write_register
    inc hl
    ld e,(hl)
    ld a,5
    call ay_write_register
    inc hl
    ld e,(hl)
    ld a,10                         ; channel C amplitude
    call ay_write_register
    inc hl
    ld (c_sound_ptr),hl
    jr check_c_finished

play_impact_frame:
    ld hl,(c_sound_ptr)
    ld e,(hl)
    ld a,6                          ; per-frame random noise period: crackle
    call ay_write_register
    inc hl
    ld e,(hl)
    ld a,10
    call ay_write_register
    inc hl
    ld (c_sound_ptr),hl
    jr check_c_finished

play_ding_frame:
    ld hl,(c_sound_ptr)
    ld e,(hl)
    ld a,10
    call ay_write_register
    inc hl
    ld (c_sound_ptr),hl

check_c_finished:
    ld a,(c_sound_left)
    or a
    ret nz
    xor a
    ld (c_sound_kind),a
    call refresh_ay_mixer
    ld a,(game_state)
    or a
    ret nz                          ; player-crash pause keeps engine silent
    ld a,255                        ; force channel A noise-period restoration
    ld (ay_last_speed),a
    ret

silence_ay:
    xor a
    ld (shot_sound_timer),a
    ld (missile_sound_left),a
    ld (c_sound_left),a
    ld (c_sound_kind),a
    ld (a_burst_left),a
    ld (siren_tone_active),a
    call refresh_ay_mixer
    ld e,0
    ld a,8
    call ay_write_register
    ld e,0
    ld a,9
    call ay_write_register
    ld e,0
    ld a,10
    call ay_write_register
    xor a
                                    ; callers may rely on a cleared accumulator
    ret

ay_write_register:
    ; Input A=register, E=value. TC2068/TS2068 expose their AY through the exact
    ; 16-bit ports $00F5/$00F6; Spectrum 128K retains $FFFD/$BFFD.
    push af
#if TIMEX_HICOLOR
    ld a,(timex_ay_present)
    or a
    jr z,skip_timex_ay_write
    pop af
    ld bc,0x00f5
    out (c),a
    ld a,e
    inc c                            ; BC=$00F6, AY data port
    out (c),a
    ret
skip_timex_ay_write:
    pop af
    ret
#else
    pop af
    ld bc,0xfffd
    out (c),a
    ld b,0xbf
    ld a,e
    out (c),a
    ret
#endif
