; Generated by tools/tia2ay.py - do not edit by hand.
; Regenerate with: python3 tools/tia2ay.py
;
; Per-frame AY register data derived from the sound behaviour of the
; original Atari 2600 River Raid (values only; see tools/tia2ay.py
; for the TIA-to-AY conversion rules).

missile_sound_frames:
    db 13

; Player missile: tone period low, high, volume per frame.
missile_sound_table:
    db 41,1,11,62,1,11,83,1,11,125,1,11
    db 146,1,11,168,1,11,210,1,11,231,1,11
    db 252,1,11,17,2,11,39,2,11,81,2,11
    db 81,2,0

impact_sound_frames:
    db 20

; Destroyed actor: noise period, volume per frame.
impact_sound_table:
    db 26,15,28,15,27,15,27,14,28,14,26,14
    db 31,14,25,13,30,13,24,13,28,12,25,12
    db 31,11,24,11,28,11,28,10,25,10,29,9
    db 25,7,25,0

crash_sound_frames:
    db 26

crash_sound_noise:
    db 31

; Life lost: channel A volume ramp over fixed coarse noise.
crash_sound_table:
    db 15,15,15,14,14,14,14,13,13,13,12,12
    db 11,11,11,10,10,9,7,7,6,6,3,1
    db 1,0

fuelout_sound_frames:
    db 29

fuelout_sound_noise:
    db 10

; Out of fuel: longer, higher-pitched variant of the life-lost burst.
fuelout_sound_table:
    db 1,1,0,15,15,15,15,14,14,14,13,13
    db 13,12,12,11,11,11,10,10,9,7,7,6
    db 6,3,1,1,0

ding_sound_frames:
    db 8

ding_period_normal:
    db 226

ding_period_full:
    db 113

; Refuelling ping volume ramp; the tone period is set at trigger time.
ding_volume_table:
    db 11,11,10,9,6,3,1,0

siren_cycle_frames:
    db 53

siren_volume:
    db 15

; Low-fuel warning cycle: tone period low, high per frame; a zero
; period hands the frame back to the engine noise.
siren_period_table:
    db 166,2,166,2,145,2,123,2,123,2,102,2
    db 102,2,81,2,60,2,60,2,39,2,39,2
    db 17,2,252,1,252,1,231,1,231,1,210,1
    db 189,1,189,1,168,1,168,1,146,1,125,1
    db 125,1,104,1,83,1,83,1,62,1,62,1
    db 0,0,0,0,0,0,0,0,0,0,0,0
    db 0,0,0,0,0,0,0,0,0,0,0,0
    db 0,0,0,0,0,0,0,0,0,0,0,0
    db 0,0,0,0,0,0,0,0,0,0

splash_sound_frames:
    db 8

; Shell splash (no Atari counterpart): tone period low, high, volume.
splash_sound_table:
    db 0,3,7,64,3,6,128,3,5,192,3,4
    db 0,4,3,64,4,2,128,4,1,192,4,0

; Jet engine at slow, normal, fast. Lower period = higher noise.
ay_engine_noise_periods:
    db 31,26,19

ay_engine_volumes:
    db 7,7,11
